# Generated by Django 4.1.5 on 2023-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='notemodel',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
