# Generated by Django 4.1.5 on 2023-01-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_content_notemodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='is_starred',
        ),
        migrations.AddField(
            model_name='notemodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
