# Generated by Django 4.1.5 on 2023-01-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoView',
        ),
    ]
