# Generated by Django 4.1.5 on 2023-01-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_rename_todoview_todomodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModels',
            new_name='TodoModel',
        ),
    ]
