# Generated by Django 4.1.5 on 2023-01-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_rename_todomodels_todomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='modified_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
