# Generated by Django 4.1.5 on 2023-01-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_alter_todomodel_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todomodel',
            table='todos',
        ),
    ]
