# Generated by Django 4.1.5 on 2023-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0008_alter_todomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
