# Generated by Django 4.1.5 on 2023-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0009_alter_todomodel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todomodel',
            table=None,
        ),
    ]
